### ISSUE TITLE
Added  /dev/null to script

### ISSUE THREAD

**Issue by cvmiller** [melato/openwrt-lxd#1]
Added to the script:
mknod -m 666 /dev/null c 1 3

#comment: 
Thanks for this script, it got me past the roadblock on running openwrt inside a LXD container. And thanks for the pointer to the build script, but alas, it is x86 focused and doesn't support ARM. I am running LXD on ARM (Raspberry Pi and Odroid), and your script got things running. thanks again.

**Comment by melato** [comment]
Thanks.
added /dev/null to init.sh, as per above.
Also link to a common init.sh for versions 18, 17.
